
#演示将配置文件中配置的每一个属性的值，映射到Person的bean中。
#person:
#  name: zhangSan
#  age: 18
#  boss: false
#  birth: 2018/04/01
#  maps:
#    k1: v1
#    k2: v2
## Map的行内写法
## maps: {k1: v1, k2: v2}
#  lists:
#   - dog
#   - cat
#   - bird
#  dog:
#   name: 大白罴
#   age: 2
